<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ItemDetail.Application\ItemDetail.Application.csproj" />
    <ProjectReference Include="..\ItemDetail.Infrastructure\ItemDetail.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
  <None Include="Data/products.json" CopyToOutputDirectory="Always" />
  </ItemGroup>


</Project>
